### ISSUE TITLE
Is That Safe To Use ?

### ISSUE THREAD

**Issue by ghost** [VennDev/SpartanPHP#1]
I've "reverse engineered" your encryption.

that's the example (Test.php): 
```php
class Test {public function __construct() {echo "Hello World!";}}$class = new Test();
```

**Comment by VennDev** [comment]
Sorry this just error encrypt

**Comment by VennDev** [comment]
so you can reve it

**Comment by VennDev** [comment]
can you test new code here

**Comment by VennDev** [comment]
https://github.com/VennDev/SpartanPHP/tree/main/code

**Comment by ghost** [comment]
Seems to be unsafe 
```php
class Test {public function __construct() {echo "Hello Guys!\n";}}$c = new Test();class Good {public function __construct() {echo "Hello Good!\n";}}$d = new Good();
```

**Comment by VennDev** [comment]
thanks y so much for your working ^^

Vào Th 5, 21 thg 3, 2024 vào lúc 05:44 ShadowMikado <
***@***.***> đã viết:
